FROM golang:1.20-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the Go modules dependency files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the application source code
COPY . .

# Build the Go application
RUN go build -o main .

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the executable
CMD ["./main"]
